apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: preprocess-score
spec:
  params:
    - name: scoreId
  steps:
    - name: preprocess-score
      image: pharmsci/preprocess:v0.2
      imagePullPolicy: IfNotPresent
      env:
      - name: TASK
        value: "Score"
      - name: RESULT_BUCKET_NAME
        value: "score"
      - name: SCORE_ID
        value: "$(params.scoreId)"
      envFrom:
        - configMapRef:
            name: pipeline-config
        - secretRef:
            name: pipeline-secret
      command: [ "python3", "entrypoint.py"]
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: preprocess-train
spec:
  params:
  - name: task
    default: "Train"
  - name: dataBucketName
    default: "data"
  - name: resultBucketName
    default: "train"
  - name: proteinName
  - name: dataPath
  - name: trimData
    default: "True"
  - name: targetName
  - name: smilesColName
  - name: log10Target
  - name: experimentCondition
  results:
    - name: FEATURES_PATH
    - name: TARGET_PATH
    - name: EXPERIMENT_NAME
  steps:
    - name: preprocess-train
      image: pharmsci/preprocess:v0.2
      imagePullPolicy: IfNotPresent
      env:
      - name: TASK
        value: "Train"
      - name: DATA_PATH
        value: "$(params.dataPath)"
      - name: DATA_BUCKET_NAME
        value: "$(params.dataBucketName)"
      - name: RESULT_BUCKET_NAME
        value: "$(params.resultBucketName)"
      - name: PROTEIN_NAME
        value: "$(params.proteinName)"
      - name: TRIM_DATA
        value: "$(params.trimData)"
      - name: SMILES_COLUMN_NAME
        value: "$(params.smilesColName)"
      - name: TARGET_NAME
        value: "$(params.targetName)"
      - name: EXPERIMENT_CONDITION
        value: "$(params.experimentCondition)"
      - name: LOG10_TARGET
        value: "$(params.log10Target)"
      - name: FEATURES_PATH_RESULT_PATH
        value: $(results.FEATURES_PATH.path)
      - name: TARGET_PATH_RESULT_PATH
        value: $(results.TARGET_PATH.path)
      - name: EXPERIMENT_NAME_RESULT_PATH
        value: $(results.EXPERIMENT_NAME.path)
      envFrom:
        - configMapRef:
            name: pipeline-config
        - secretRef:
            name: pipeline-secret
      command: ["python", "entrypoint.py"]
      args: [
        "-f",
        "results.FEATURES_PATH.path",
        "-t",
        "results.TARGET_PATH.path",
        "-e",
        "results.EXPERIMENT_NAME.path"
        ]
