apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: score
spec:
  params:
    - name: modelPath
    - name: featuresPath
    - name: smilesPath
    - name: scoreId
  results:
    - name: resultsPath
  steps:
    - name: score
      image: pharmsci/score:v0.1
      imagePullPolicy: IfNotPresent
      env:
      - name: MODEL_PATH
        value: "$(params.modelPath)"
      - name: MODEL_BUCKET_NAME
        value: "mlflow"
      - name: FEATURES_BUCKET_NAME
        value: "score"
      - name: FEATURES_PATH
        value: "$(params.featuresPath)"
      - name: SMILES_PATH
        value: "$(params.smilesPath)"
      - name: SCORE_ID
        value: "$(params.scoreId)"
      - name: RESULTS_PATH_RESULT_PATH
        value: $(results.RESULTS_PATH.path)
      envFrom:
        - configMapRef:
            name: preprocess
      command: ["python3", "entrypoint.py"]