apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: train
spec:
  params:
    - name: resultBucketName
    - name: targetPath
    - name: featuresPath
    - name: proteinName
    - name: experimentName
    - name: numRuns
      default: "10"
    - name: numSplits
      default: "5"
    - name: randomState
      default: "42"
    - name: mode
      default: "regression"
    - name: metric
      default: "r2_score"
    - name: metricMode
      default: "max"
    - name: testSize
      default: "0.2"
  steps:
    - name: train
      image: pharmsci/train:v0.1
      imagePullPolicy: IfNotPresent
      env:
      - name: FEATURES_PATH
        value: "$(params.featuresPath)"
      - name: TARGET_PATH
        value: "$(params.targetPath)"
      - name: PROTEIN_NAME
        value: "$(params.proteinName)"
      - name: EXPERIMENT_NAME
        value: "$(params.experimentName)"
      - name: RESULT_BUCKET_NAME
        value: "$(params.resultBucketName)"
      - name: NUM_RUNS
        value: "$(params.numRuns)"
      - name: NUM_SPLITS
        value: "$(params.numSplits)"
      - name: RANDOM_STATE
        value: "$(params.randomState)"
      - name: MODE
        value: "$(params.mode)"
      - name: METRIC
        value: "$(params.metric)"
      - name: METRIC_MODE
        value: "$(params.metricMode)"
      - name: TEST_SIZE
        value: "$(params.testSize)"
      envFrom:
        - configMapRef:
            name: preprocess
      command: [ "python3", "entrypoint.py"]