apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: validate-pipeline
spec:
  params:
    - name: status
    - name: scoreId
  steps:
    - name: validate-pipeline
      image: pharmsci/validate-pipeline:v0.1
      imagePullPolicy: IfNotPresent
      env:
      - name: STATUS
        value: "$(params.status)"
      - name: SCORE_ID
        value: "$(params.scoreId)"
      envFrom:
        - configMapRef:
            name: preprocess
      command: ["python3", "entrypoint.py"]