apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: lupuslucis.fvds.ru
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: mlflow-svc
            port:
              number: 5000
  - host: s3.lupuslucis.fvds.ru
    http:
        paths:
        - path: "/"
          pathType: Prefix
          backend:
            service:
              name: minio-ui-svc
              port:
                number: 9090
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: tekton-pipelines
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: tekton.lupuslucis.fvds.ru
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: tekton-dashboard
            port:
              number: 9097
