apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: production
data:
  SCORE_EVENT_LISTENER_URL: "http://el-score-eventlistener:8080"
  DB_HOST: "mongo-svc"
  DB_PORT: "27017"
  DB_NAME: "main_db"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: production
data:
  API_URL: "http://api.lupuslucis.fvds.ru/"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: tracking
data:
  POSTGRES_USER: "postgresadmin"
  POSTGRES_DB: "mlflowdb"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-config
  namespace: tracking
data:
  MINIO_ROOT_USER: "minioadmin"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mlflow-config
  namespace: tracking
data:
MLFLOW_S3_ENDPOINT_URL: "http://minio-api-svc:9000/"
AWS_ACCESS_KEY_ID: "minioadmin"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-config
  namespace: production
data:
  MONGO_INITDB_ROOT_USERNAME: "root"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-express-config
  namespace: production
data:
  ME_CONFIG_BASICAUTH_USERNAME: expressadmin
  ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
  ME_CONFIG_MONGODB_ADMINUSERNAME: "root"
  ME_CONFIG_MONGODB_PORT: "27017"
  ME_CONFIG_MONGODB_SERVER: mongo-svc



