apiVersion: v1
kind: ConfigMap
metadata:
  name: preprocess
data:
  S3_ENDPOINT_URL: "http://minio-api-svc:9000"
  AWS_ACCESS_KEY_ID: "minioadmin"
  AWS_SECRET_ACCESS_KEY: "minioadmin"
  MLFLOW_TRACKING_URI: "http://mlflow-svc:5000/"
  MLFLOW_S3_ENDPOINT_URL: "http://minio-api-svc:9000"
  SCORE_EVENT_LISTENER_URL: "http://el-score-eventlistener:8080"
  DB_HOST: "mongo-svc"
  DB_PORT: "27017"
  DB_USER: "root"
  DB_PASSWORD: "root"
  DB_NAME: "main_db"