apiVersion: v1
kind: Pod
metadata:
  name: dev
  labels:
    app: mlflow
spec:
  containers:
    - name: python
      image: python
      command: ["sleep", "5000"]
      env:
        - name: MLFLOW_S3_ENDPOINT_URL
          value: http://minio-api-svc:9000/
        - name: AWS_ACCESS_KEY_ID
          value: "minioadmin"
        - name: AWS_SECRET_ACCESS_KEY
          value: "minioadmin"
---
apiVersion: v1 
kind: Service
metadata: 
  name: dev-svc
spec:
  type: NodePort
  selector:
    app: mlflow
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
      nodePort: 30002
