apiVersion: v1
kind: Pod
metadata: 
  name: postgresql
  labels:
    app: postgresql
spec:
  containers:
    - name: postgresql
      image: postgres:15.0
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_USER
          value: postgresadmin
        - name: POSTGRES_PASSWORD
          value: postgresadmin
        - name: POSTGRES_DB
          value: mlflowdb
---
apiVersion: v1
kind: Service
metadata: 
  name: postgresql-svc
spec:
  selector:
    app: postgresql
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP