apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: tracking
  labels:
    app: postgresql
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /k8s_volumes/postgres
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv
  namespace: tracking
  labels:
    app: minio
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /k8s_volumes/minio
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  namespace: production
  labels:
    app: mongo
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /k8s_volumes/mongo