apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: score
spec:
  description: >-
    perform preprocessing and scoring
  params:
    - name: scoreId
  tasks:
  - name: preprocess
    params:
    - name: scoreId
      value: $(params.scoreId)
    taskRef:
      kind: Task
      name: preprocess-score
  - name: score
    params:
    - name: scoreId
      value: $(params.scoreId)
    - name: featuresPath
      value: $(tasks.preprocess.results.FEATURES_PATH)
    taskRef:
      kind: Task
      name: score
    runAfter:
      - preprocess
  finally:
    - name: generate-response
      params:
      - name: status
        value: $(tasks.status)
      - name: scoreId
        value: $(params.scoreId)
      taskRef:
        name: generate-response