apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: score
spec:
  description: >-
    perform preprocessing and scoring
  params:
    - name: smiles
    - name: scoreId
    - name: modelPath
  tasks:
  - name: preprocess
    params:
    - name: smiles
      value: $(params.smiles)
    - name: scoreId
      value: $(params.scoreId)
    taskRef:
      kind: Task
      name: preprocess-score
  - name: score
    params:
    - name: modelPath
      value: $(params.modelPath)
    - name: modelPath
      value: $(params.smiles)
    - name: scoreId
      value: $(params.scoreId)
    - name: featuresPath
      value: $(tasks.preprocess.results.FEATURES_PATH)
    - name: smilesPath
      value: $(tasks.preprocess.results.SMILES_PATH)
    taskRef:
      kind: Task
      name: score
    runAfter:
      - preprocess
  finally:
    - name: generate_response
      params:
      - name: status
        value: $(tasks.status)
      - name: resultsPath
        value: tasks.score.results.RESULTS_PATH
      - name: smilesPath
        value: $(tasks.preprocess.results.SMILES_PATH)
      - name: scoreId
        value: $(params.scoreId)
      - name: resultBucketName
        value: "score"
      taskRef:
        name: generate_response