apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: preprocess
spec:
  params:
    - name: dataPath
      type: string
      default: "datasets/data.csv"
  steps:
    - name: preprocess
      image: pharmsci/preprocess:v0.1
      imagePullPolicy: IfNotPresent
      env:
      - name: DATA_PATH
        value: "$(params.dataPath)"
      envFrom:
        - configMapRef:
            name: preprocess
      command: [ "python3", "preprocess.py"]
