apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: preprocess-score
spec:
  params:
    - name: smiles
      type: string
    - name: featuresPath
      type: string
  steps:
    - name: preprocess-score
      image: pharmsci/preprocess:v0.2
      imagePullPolicy: IfNotPresent
      env:
      - name: TASK
        value: "Score"
      - name: SMILES
        value: "$(params.smiles)"
      - name: BUCKET_NAME
        value: "score"
      - name: FEATURES_PATH
        value: "$(params.featuresPath)"
      envFrom:
        - configMapRef:
            name: preprocess
      command: [ "python3", "entrypoint.py"]
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: preprocess-train
spec:
  params:
    - name: dataPath
      type: string
    - name: trimData
      type: string
      default: "True"
    - targetPath:
      type: string
    - name: featuresPath
      type: string
    - name: bucketName
      type: string
    - name: targetName
      type: string
      default: "standard_value"
    - name: smilesColumnName
      type: string
      default: "canonical_smiles"
    - name: log10Target
      type: string
      default: "False"
  steps:
    - name: preprocess-score
      image: pharmsci/preprocess:v0.2
      imagePullPolicy: IfNotPresent
      env:
      - name: TASK
        value: "Train"
      - name: DATA_PATH
        value: "$(params.dataPath)"
      - name: TRIM_DATA
        value: "$(params.trimData)"
      - name: TARGET_PATH
        value: "$(params.targetPath)"
      - name: BUCKET_NAME
        value: "$(params.bucketName)"
      - name: FEATURES_PATH
        value: "$(params.featuresPath)"
      - name: TARGET_NAME
        value: "$(params.targetName)"
      - name: SMILES_COLUMN_NAME
        value: "$(params.smilesColumnName)"
      - name: LOG10_TARGET
        value: "$(params.log10Target)"
      envFrom:
        - configMapRef:
            name: preprocess
      command: [ "python3", "entrypoint.py"]
