apiVersion: v1
kind: Deployment
metadata:
  name: frontend
  namespace: production
  labels:
    app: frontend
spec:
  replicas: 3
    strategy:
      type: RollingUpdate
    selector:
      matchLabels:
        app: frontend
    template:
      metadata:
        labels:
          app: frontend
      spec:
        containers:
          - name: frontend
            image: pharmsci/checkmol-frontend:v0.1
            envFrom:
            - configMapRef:
                name: frontend-config
            command: [
              "node",
              "app.js"
            ]
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: production
spec:
  selector:
    app: frontend
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000