apiVersion: v1
kind: Deployment
metadata:
  name: minio
  namespace: tracking
  labels:
    app: minio
spec:
  replicas: 1
    strategy:
      type: RollingUpdate
    selector:
      matchLabels:
        app: mongo
    template:
      metadata:
        labels:
          app: mongo
      spec:
        containers:
          - name: minio
            image: minio/minio:RELEASE.2022-12-02T19-19-22Z
            command:
              - /bin/bash
              - -c
            args:
              - minio server /data --console-address :9090
            envFrom:
                - configMapRef:
                    name: minio-config
                - secretRef:
                    name: minio-secret
            volumeMounts:
              - mountPath: /data
                  volumes: minio-volume
        volumes:
          - name: mongo-volume
            persistentVolumeClaim:
              claimName: minio-pvc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
  namespace: tracking
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  selector:
    matchLabels:
      app: minio

---
apiVersion: v1
kind: Service
metadata:
  name: minio-api-svc
  namespace: tracking
spec:
  selector:
    app: minio
  ports:
    - port: 9000
      protocol: TCP
      targetPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: minio-ui-svc
  namespace: tracking
spec:
  selector:
    app: minio
  ports:
    - port: 9090
      protocol: TCP
      targetPort: 9090
