apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-server
  namespace: tracking
  labels:
    app: mlflow-server
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: mlflow-server
  template:
    metadata:
      labels:
        app: mlflow-server
    spec:
      containers:
        - name: mlflow-server
          image: pharmsci/mlflow-server:v0.2
          command: [
            "mlflow",
            "server",
            "--host",
            "0.0.0.0",
            "--backend-store-uri",
            "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgresql-svc:5432/$(POSTGRES_DB)",
            "--default-artifact-root",
            "s3://mlflow/"
          ]
          envFrom:
            - configMapRef:
                name: mlflow-config
            - configMapRef:
                name: postgres-config
            - secretRef:
                name: mlflow-secret
            - secretRef:
                name: postgres-secret
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow-svc
  namespace: tracking
spec:
  selector:
    app: mlflow-server
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
