apiVersion: v1
kind: Pod
metadata:
  name: api
  labels:
    app: api
spec:
  containers:
    - name: api
      image: pharmsci/api:v0.1
      command: [
        "uvicorn",
        "main:app",
        "--host",
        "0.0.0.0",
        "--port 8000"
      ]
---
apiVersion: v1
kind: Service
metadata:
  name: api-svc
spec:
  selector:
    app: api
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000