apiVersion: v1
kind: Pod
metadata:
  name: dev
  labels:
    app: dev
spec:
  containers:
    - name: dev
      image: pharmsci/train:v0.1
      command: ["sleep", "infinity"]
      env:
        - name: MLFLOW_S3_ENDPOINT_URL
          value: http://minio-api-svc:9000/
        - name: AWS_ACCESS_KEY_ID
          value: "minioadmin"
        - name: AWS_SECRET_ACCESS_KEY
          value: "minioadmin"
      resources:
        requests:
          memory: "1Gi"
          cpu: "1"
        limits:
          memory: "2Gi"
          cpu: "2"
      volumeMounts:
        - mountPath: /projects
          name: dev-volume
  volumes:
    - name: dev-volume
      persistentVolumeClaim:
        claimName: dev-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: dev-svc
spec:
  type: NodePort
  selector:
    app: dev
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
      nodePort: 30002
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dev-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  selector:
    matchLabels:
      app: dev

