apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  containers:
    - name: frontend
      image: pharmsci/checkmol-frontend:v0.1
      envFrom:
      - configMapRef:
          name: preprocess
      command: [
        "node",
        "app.js"
      ]
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
spec:
  selector:
    app: frontend
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000