apiVersion: v1
kind: Pod
metadata:
  name: minio
  labels:
    app: minio
spec:
  containers:
  - name: minio
    image: quay.io/minio/minio:latest
    command:
    - /bin/bash
    - -c
    args:
    - minio server /data --console-address :9090
---
apiVersion: v1
kind: Service
metadata:
  name: minio-api-svc
spec:
  selector:
    app: minio
  ports:
    - port: 9000
      protocol: TCP
      targetPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: minio-ui-svc
spec:
  selector:
    app: minio
  ports:
    - port: 9090
      protocol: TCP
      targetPort: 9090
