apiVersion: v1
kind: Pod
metadata:
  name: mlflow-server
  labels:
    app: mlflow-server
spec:
  containers:
    - name: mlflow-server
      image: pharmsci/mlflow-server:v0.2
      command: [
        "mlflow",  
        "server",  
        "--host", 
        "0.0.0.0", 
        "--backend-store-uri", 
        "postgresql://postgresadmin:postgresadmin@postgresql-svc:5432/mlflowdb",
        "--default-artifact-root",
        "s3://mlflow/"
      ]
      env:
        - name: MLFLOW_S3_ENDPOINT_URL
          value: http://minio-api-svc:9000/
        - name: AWS_ACCESS_KEY_ID
          value: "minioadmin"
        - name: AWS_SECRET_ACCESS_KEY
          value: "minioadmin"
---
apiVersion: v1 
kind: Service
metadata: 
  name: mlflow-svc
spec:
  selector:
    app: mlflow-server
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
